package dmitriy.losev.students.core.exception

internal const val PHONE_NUMBER_VALIDATION_EXCEPTION_CODE = 30001
internal const val EMAIL_VALIDATION_EXCEPTION_CODE = 30002
internal const val GET_STUDENT_EXCEPTION_CODE = 30003
internal const val EMPTY_PHONE_NUMBER_EXCEPTION_CODE = 30004
internal const val STUDENT_IS_NOT_LOADING_EXCEPTION_CODE = 30005
internal const val CONTACT_IS_NOT_LOADING_EXCEPTION_CODE = 30006
internal const val EMPTY_SKYPE_EXCEPTION_CODE = 30007
internal const val EMPTY_DISCORD_EXCEPTION_CODE = 30008
internal const val EMPTY_EMAIL_EXCEPTION_CODE = 30009
internal const val WHATS_APP_APPLICATION_IS_NOT_INSTALLED_EXCEPTION_CODE = 30010
internal const val SKYPE_APPLICATION_IS_NOT_INSTALLED_EXCEPTION_CODE = 30011
internal const val VIBER_APPLICATION_IS_NOT_INSTALLED_EXCEPTION_CODE = 30012
internal const val TELEGRAM_APPLICATION_IS_NOT_INSTALLED_EXCEPTION_CODE = 30013
internal const val EMPTY_FIRST_NAME_EXCEPTION_CODE = 30014
