package dmitriy.losev.profile.core.exception

internal const val USER_AVAILABLE_EXCEPTION_CODE = 20001
internal const val EMPTY_EMAIL_EXCEPTION_CODE = 20002
internal const val EMAIL_VALIDATION_EXCEPTION_CODE = 20003
internal const val EMPTY_PASSWORD_EXCEPTION_CODE = 20004
internal const val MIN_LENGTH_PASSWORD_EXCEPTION_CODE = 20005
internal const val MAX_LENGTH_PASSWORD_EXCEPTION_CODE = 20006
internal const val PASSWORD_LOWER_CASE_LETTER_EXCEPTION_CODE = 20007
internal const val PASSWORD_UPPER_CASE_LETTER_EXCEPTION_CODE = 20008
internal const val DIFFERENT_PASSWORDS_EXCEPTION_CODE = 20009
internal const val FIREBASE_AUTH_EXCEPTION_CODE = 20010
