package dmitriy.losev.profile.core.exception

internal const val USER_ABSENCE_EXCEPTION_CODE = 20000
internal const val USER_AVAILABLE_EXCEPTION_CODE = 20001

internal const val EMPTY_PASSWORD_EXCEPTION_CODE = 20010
internal const val EMPTY_OLD_PASSWORD_EXCEPTION_CODE = 20011
internal const val EMPTY_NEW_PASSWORD_EXCEPTION_CODE = 20012

internal const val INVALID_PHONE_NUMBER_EXCEPTION_CODE = 20020

internal const val MIN_LENGTH_PASSWORD_EXCEPTION_CODE = 20005
internal const val MAX_LENGTH_PASSWORD_EXCEPTION_CODE = 20006
internal const val PASSWORD_LOWER_CASE_LETTER_EXCEPTION_CODE = 20007
internal const val PASSWORD_UPPER_CASE_LETTER_EXCEPTION_CODE = 20008
internal const val DIFFERENT_PASSWORDS_EXCEPTION_CODE = 20009
internal const val SIMILAR_OLD_AND_NEW_PASSWORDS_EXCEPTION_CODE = 20030
internal const val FIREBASE_AUTH_EXCEPTION_CODE = 20014

internal const val EMPTY_EMAIL_EXCEPTION_CODE = 20100
internal const val EMPTY_OLD_EMAIL_EXCEPTION_CODE = 20101
internal const val EMPTY_NEW_EMAIL_EXCEPTION_CODE = 20102
internal const val EMAIL_VALIDATION_EXCEPTION_CODE = 20103
internal const val OLD_EMAIL_VALIDATION_EXCEPTION_CODE = 20104
internal const val NEW_EMAIL_VALIDATION_EXCEPTION_CODE = 20105

