package dmitriy.losev.firebase.core

internal const val EMPTY_STRING = ""
internal const val FIREBASE_DATABASE = "https://tutorsschedule-2305f-default-rtdb.europe-west1.firebasedatabase.app/"
internal const val FIREBASE_STORAGE = "gs://tutorsschedule-2305f.appspot.com"
internal const val FIREBASE_PROJECT_ID = "tutorsschedule-2305f"
internal const val FIREBASE_APPLICATION_ID = "1:99277636920:android:000797c1b3f1f2d4b0edcd"
internal const val FIREBASE_STORAGE_BUCKET = "tutorsschedule-2305f.appspot.com/"
internal const val API_KEY = "AIzaSyC_Z0luLcaol8WAitXZt2pkhNRrpebAk4g"

internal const val AVATARS = "avatars"
internal const val STUDENTS = "students"
internal const val CONTACTS = "contacts"
internal const val GROUPS = "groups"
internal const val SUBJECTS = "subjects"
internal const val LESSONS = "lessons"
internal const val TASKS = "tasks"
internal const val PERIODS = "periods"
internal const val FIRST_NAME = "first_name"
internal const val LAST_NAME = "last_name"
internal const val PATRONYMIC = "patronymic"
internal const val PHONE_NUMBER = "phone_number"