package dmitriy.losev.firebase.core.exception


const val GOOGLE_AUTH_IS_NOT_SUCCESS = 10014
const val FIREBASE_AUTH_INVALID_USER_EXCEPTION = 10015
const val FIREBASE_AUTH_INVALID_CREDENTIALS_EXCEPTION = 10016
const val FIREBASE_TOO_MANY_REQUESTS_EXCEPTION = 10017
const val EMPTY_USER_DATA = 10018
const val UNSUPPORTED_API_CALL_EXCEPTION = 10019
const val FIREBASE_AUTH_USER_COLLISION_EXCEPTION_CODE = 10024
const val UPDATE_USER_DATE_EXCEPTION_CODE = 10025
const val UPLOAD_AVATAR_EXCEPTION_CODE = 10001