package dmitriy.losev.firebase.core.exception


const val GOOGLE_AUTH_IS_NOT_SUCCESS_EXCEPTION_CODE = 10014
const val FIREBASE_AUTH_INVALID_USER_EXCEPTION_CODE = 10015
const val FIREBASE_AUTH_INVALID_CREDENTIALS_EXCEPTION_CODE = 10016
const val FIREBASE_TOO_MANY_REQUESTS_EXCEPTION_CODE = 10017
const val EMPTY_USER_DATA = 10018
const val UNSUPPORTED_API_CALL_EXCEPTION = 10019
const val API_EXCEPTION_CODE = 10020
const val FIREBASE_AUTH_USER_COLLISION_EXCEPTION_CODE = 10024
const val UPDATE_USER_DATE_EXCEPTION_CODE = 10025
const val UPLOAD_AVATAR_EXCEPTION_CODE = 10001
const val TOKEN_AUTHENTICATION_EXCEPTION_CODE = 10002
const val DISPLAY_NAME_IS_NULL_EXCEPTION_CODE = 10003
const val AVATAR_URI_IS_NULL_EXCEPTION_CODE = 10004
const val EMAIL_IS_NULL_EXCEPTION_CODE = 10005
const val USER_NOT_AUTHORIZATION_EXCEPTION_CODE = 10006
const val NO_PROVIDERS_EXCEPTION_CODE = 10007
const val FIREBASE_AUTH_RECENT_LOGIN_REQUIRED_EXCEPTION_CODE = 10008
const val FIREBASE_AUTH_WEAK_PASSWORD_EXCEPTION_CODE = 10030

const val STUDENT_ADD_EXCEPTION_CODE = 10100
const val GROUP_ADD_EXCEPTION_CODE = 10101
const val SUBJECT_ADD_EXCEPTION_CODE = 10102
const val LESSON_ADD_EXCEPTION_CODE = 10103
const val PERIOD_ADD_EXCEPTION_CODE = 10104
const val TASK_ADD_EXCEPTION_CODE = 10105
const val CONTACT_ADD_EXCEPTION_CODE = 10106

const val NULLABLE_STUDENT_EXCEPTION_CODE = 10200
const val NULLABLE_GROUP_EXCEPTION_CODE = 10201
const val NULLABLE_SUBJECT_EXCEPTION_CODE = 10202
const val NULLABLE_LESSON_EXCEPTION_CODE = 10203
const val NULLABLE_PERIOD_EXCEPTION_CODE = 10204
const val NULLABLE_TASK_EXCEPTION_CODE = 10205
const val NULLABLE_CONTACT_EXCEPTION_CODE = 10206