package dmitriy.losev.ui.theme.colors

internal val darkColors = TutorsScheduleColors(
    backgroundPrimary = BackgroundBlack,
    backgroundSecondary = BackgroundBlack,
    backgroundTitle = SecondBlack,
    iconPrimary = MainBlue,
    iconSecondary = Gray2,
    backgroundIconPrimary = SecondBlack,
    backgroundIconSecondary = SecondBlack,
    textPrimary = White,
    textSecondary = White,
    textHint = Gray2,
    backgroundSwitch = SecondBlack,
    backgroundSelectedSwitch = MainBlue,
    switch = Gray7,
    selectedSwitch = White,
    textFieldEmptyBackground = Gray5,
    textFieldBackground = SecondBlack,
    textFieldBorder = Gray3,
    textFieldFocusedBorder = BlueForTitle,
    textFieldCursor = CursorBlue,
    textFieldHint = Gray2,
    primaryButtonBackground = MainBlue,
    secondaryButtonBackground = SecondBlack,
    primaryButtonText = White,
    secondaryButtonText = White,
    hintButtonText = MainBlue,
    criticalButtonText = Red,
    subjectsBackground = SecondBlack,
    popUpBackground = BackgroundBlack,
    menuBackground = MainBlue,
    menuSelectedBackground = BottomBarSelectedDarkBlue,
    menu = White,
    statusBar = StatusBarBlack,
    filterPrimary = LightBlue,
    filterSecondary = SecondGray,
    filter = SecondGray,
    filterTextColor = Black
)

