package dmitriy.losev.auth.core.exceptions

const val EMPTY_PASSWORD_EXCEPTION_CODE = 1004
const val MIN_LENGTH_PASSWORD_EXCEPTION_CODE = 1005
const val MAX_LENGTH_PASSWORD_EXCEPTION_CODE = 1006
const val PASSWORD_LOWER_CASE_LETTER_EXCEPTION_CODE = 1007
const val PASSWORD_UPPER_CASE_LETTER_EXCEPTION_CODE = 1008
const val DIFFERENT_PASSWORDS_EXCEPTION_CODE = 1009
const val USER_NOT_FOUND = 1011
const val EMAIL_AUTH_IS_NOT_SUCCESS = 1012
const val ANONYMOUS_AUTH_IS_NOT_SUCCESS = 1013
const val GOOGLE_AUTH_IS_NOT_SUCCESS = 1014
const val FIREBASE_AUTH_INVALID_USER_EXCEPTION = 1015
const val FIREBASE_AUTH_INVALID_CREDENTIALS_EXCEPTION = 1016
const val FIREBASE_TOO_MANY_REQUESTS_EXCEPTION = 1017
const val EMPTY_USER_DATA = 1018
const val UNSUPPORTED_API_CALL_EXCEPTION = 1019
const val MAX_LENGTH_FIRST_NAME_EXCEPTION_CODE = 1020
const val MAX_LENGTH_LAST_NAME_EXCEPTION_CODE = 1021
const val EMPTY_EMAIL_EXCEPTION_CODE = 1022
const val INVALID_EMAIL_EXCEPTION_CODE = 1023
const val FIREBASE_AUTH_USER_COLLISION_EXCEPTION_CODE = 1024
const val UPDATE_USER_DATE_EXCEPTION_CODE = 1025